---
apiVersion: networking.gloo.solo.io/v2
kind: ExternalEndpoint
metadata:
  name: fake-idp
  namespace: gloo-mesh
  labels:
    external-service: fake-idp
spec:
  address: bdlilley.github.io
  ports:
    - name: https
      number: 443
---
apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: fake-idp
  namespace: gloo-mesh
spec:
  selector:
    external-service: fake-idp
  hosts:
  - bdlilley.github.io
  ports:
  - name: https
    number: 443
    protocol: HTTPS
    clientsideTls: {}